[package]
name = "aoc_day_02"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.*", features = ["derive", "string"] }
thiserror = "2.*"
tokio = { version = "1.*", features = ["full"] }
