[package]
name = "advent-of-code-2023-day-7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuffle = "0.1.7"
rand = "0.8.5"